deployment_target = '15.0'
target 'iosApp' do
    use_frameworks!
    platform :ios, deployment_target
    # Pods for iosApp
    pod 'FirebaseCore', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :tag => '11.14.0'
    pod 'FirebaseAIBridge', :git => 'https://github.com/SeanChinJunKai/FirebaseAIBridge', :tag => '0.1.0'
end
